### ISSUE TITLE
Add process page for Github

### ISSUE THREAD

**Issue by darthtrevino** [atsid/engineering#12]
* Git-Flow link
* Github commit log format (https://github.com/atsid/generator-ats-node-webapp/blob/master/generators/git-hooks/templates/scripts/git/hooks/commit-msg)
* How to write a good commit message http://chris.beams.io/posts/git-commit/

**Comment by bmathews** [comment]
https://github.com/atsid/engineering/blob/master/github.md

**Comment by darthtrevino** [comment]
derp
