### ISSUE TITLE
Fix travis build so it only publishes master

### ISSUE THREAD

**Issue by natoverse** [atsid/engineering#20]
The branches: master config is apparently not working - my last PR got published to gh-pages automatically, but should not have done so until merge to master.

**Comment by natoverse** [comment]
I fixed this by simply turning on PR builds on Travis. If we end up with any code that requires quality checks to run, we can use some of the solutions discussed on these pages:

http://docs.travis-ci.com/user/pull-requests/
http://stackoverflow.com/questions/21076678/disable-travis-ci-for-pull-requests

The issue wasn't that branches:master doesn't work - travis was *not* incorrectly building branches. The issue is that PRs are a merge-master locally on travis, which means the branches:master config doesn't apply.

**Comment by rickleegit** [comment]
Hey man. Sadly, you should probably drop my account front the GitHub repos.
