### ISSUE TITLE
Make the site pretty

### ISSUE THREAD

**Issue by natoverse** [atsid/engineering#4]
For this I was thinking we could basically fork the styles of the new ATS website, but then tweak them slightly to add some uniqueness. E.g., keep the main branding, but put our own engineering twist on it. I'm thinking of examples like Facebook and Airbnb here.

**Comment by bmathews** [comment]
inspiration: 

http://adobe.github.io/
http://airbnb.io/
http://opensource.box.com/
https://code.facebook.com/
http://groupon.github.io/
http://shopify.github.io/
http://palantir.github.io/

**Comment by natoverse** [comment]
@bingles made it pretty.
