### ISSUE TITLE
Add vagrant/docker config

### ISSUE THREAD

**Issue by natoverse** [atsid/engineering#5]
Testing the full jekyll site locally will be much easier and more consistent.

**Comment by bmathews** [comment]
https://github.com/atsid/www.atsid.com/blob/gh-pages/Vagrantfile
https://github.com/atsid/www.atsid.com/tree/gh-pages/salt

**Comment by natoverse** [comment]
Since we already have those examples, I'm just going to grab them and roll this into issue #1.
